<%@ Page Title="Rules" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ManageRules.aspx.cs" Inherits="ManageRules" %>


<asp:Content ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent" runat="Server">
</asp:Content>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="Server">
    <table>
        <tr>
            <th colspan="2">Create Formula</th>
        </tr>
        <tr>
            <td></td>
            <td>
                <asp:Label ID="FormulaStatus" runat="server" Text="" /></td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>
                <asp:TextBox ID="FormulaNameTextBox" runat="server" /></td>
        </tr>
        <tr>
            <td>Formula:</td>
            <td>
                <asp:TextBox ID="FormulaTextBox" runat="server" /></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <asp:Button ID="CheckFormulaButton" Text="Check Formula" runat="server" OnClick="CheckFormulaButton_Click" />
                <asp:Button ID="SaveFormulaButton" Text="Save Formula" runat="server" OnClick="SaveFormulaButton_Click" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:LinkButton
                    ID="ShowScoringIdentifiersButton"
                    OnClick="ShowScoringIdentifiersButton_Click"
                    Text="Show City Value Identifiers"
                    runat="server" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:GridView
                    ID="ScoringIdentifiersGridview"
                    ItemType="CompareCity.Model.ScoringIdentifier"
                    SelectMethod="ScoringIdentifiersGridview_GetData"
                    AllowSorting="true"
                    AutoGenerateColumns="false"
                    Visible="false"
                    HeaderStyle-CssClass="gridview-header-row"
                    RowStyle-CssClass="identifier-table-gridview-row"
                    runat="server">
                    <Columns>
                        <asp:BoundField DataField="Name" SortExpression="Name" HeaderText="Identifier" />
                        <asp:BoundField DataField="ShortName" SortExpression="ShortName" HeaderText="Short Name" />
                        <asp:BoundField DataField="Descrition" SortExpression="Descrition" HeaderText="Description" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <th colspan="2">Your Formulas</th>
        </tr>
        <tr>
            <td colspan="2">
                <asp:GridView
                    ItemType="CompareCity.Model.RuleSet"
                    ID="RuleSetsView"
                    runat="server"
                    SelectMethod="GetRules"
                    AllowSorting="true"
                    AutoGenerateColumns="false"
                    AutoGenerateDeleteButton="true"
                    DeleteMethod="RuleSetsView_DeleteItem"
                    DataKeyNames="RuleSetId"
                    RowStyle-CssClass="gridview-row"
                    HeaderStyle-CssClass="gridview-header-row"
                    OnRowCommand="RuleSetsView_RowCommand">
                    <Columns>
                        <asp:BoundField DataField="RuleSetName" HeaderText="Name" SortExpression="RuleSetName" />
                        <asp:BoundField DataField="Formula" HeaderText="Formula" SortExpression="Formula" />
                        <asp:BoundField DataField="Valid" HeaderText="Valid?" SortExpression="Valid" />
                        <asp:ButtonField ButtonType="Link" Text="Copy Formula" CommandName="CopyFormula" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

